// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/file/ActionBar.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FilePath: typeof import('./src/components/file/FilePath.vue')['default']
    IconMenu: typeof import('~icons/ic/on-menu')['default']
    IcOutlineFolder: typeof import('~icons/ic/outline-folder')['default']
    IIcBaselinePlus: typeof import('~icons/ic/baseline-plus')['default']
    IIcOutlineDelete: typeof import('~icons/ic/outline-delete')['default']
    IIcOutlineFileUpload: typeof import('~icons/ic/outline-file-upload')['default']
    IIcOutlineFolder: typeof import('~icons/ic/outline-folder')['default']
    IIcOutlineShare: typeof import('~icons/ic/outline-share')['default']
    IMaterialSymbolsUploadRounded: typeof import('~icons/material-symbols/upload-rounded')['default']
    IRiDeleteBin5Line: typeof import('~icons/ri/delete-bin5-line')['default']
    IRiFolder2Line: typeof import('~icons/ri/folder2-line')['default']
    IRiShareLine: typeof import('~icons/ri/share-line')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    RiFolder2Line: typeof import('~icons/ri/folder2-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
