// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionBar: typeof import('./components/file/ActionBar.vue')['default']
    DetailPane: typeof import('./components/file/DetailPane.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FilePath: typeof import('./components/file/FilePath.vue')['default']
    FileTable: typeof import('./components/file/FileTable.vue')['default']
    IIcBaselineClose: typeof import('~icons/ic/baseline-close')['default']
    IIcOutlineInfo: typeof import('~icons/ic/outline-info')['default']
    IIcOutlinePeopleAlt: typeof import('~icons/ic/outline-people-alt')['default']
    IRiDeleteBin5Line: typeof import('~icons/ri/delete-bin5-line')['default']
    IRiFile3Line: typeof import('~icons/ri/file3-line')['default']
    IRiFolder2Line: typeof import('~icons/ri/folder2-line')['default']
    NavDrawer: typeof import('./components/NavDrawer.vue')['default']
    NavHeader: typeof import('./components/NavHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
